# Generated by Django 4.2.3 on 2023-08-04 00:54

import dashboard.canadian_zip_validator
import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255, validators=[dashboard.models.validate_street_address])),
                ('city', models.CharField(max_length=255, validators=[dashboard.models.validate_city])),
                ('province', models.CharField(blank=True, choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NF', 'Newfoundland'), ('YT', 'Yukon'), ('NS', 'Nova Scotia'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('NU', 'Nunavut'), ('NT', 'Northwest Territories')], default=None, max_length=2, null=True)),
                ('zip_code', models.CharField(max_length=7, validators=[dashboard.canadian_zip_validator.validate_canadian_zip])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
