# Generated by Django 4.2.3 on 2023-11-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_shipping_address',
            field=models.BooleanField(default=True),
        ),
    ]
