# Generated by Django 4.2.3 on 2023-11-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Is_active',
            field=models.BooleanField(default=True),
        ),
    ]
