# Generated by Django 4.2.3 on 2023-11-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Is_active',
        ),
    ]
