# Generated by Django 4.2.3 on 2023-08-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='slud',
            new_name='slug',
        ),
    ]
