# Generated by Django 4.2.3 on 2023-08-13 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_options_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subdirectory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
